sudo: false
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester@^5.0.0
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: wGNRz94sFo89ccmCngutDlrMmCU8sfYuItMS6iPOSVASjtGX4tzS0nSH+AzWenDaGjc8HdQJd3H13paFRedcxPDSAkJ/A0Co8QYoeKtuUDQnGX0HUQ0jgDkA+WgYePg+yhojDtS/9EuzPqSRG6MgHQDbZSXlUpsfTZPC4vswocWs76PY/BdaZ6kp3LaKZ2AIsD6F0SxA6IlCFOsgPkgTjxg/yVoy7F8lDUbcNwTuhU6OjI2QNwe5qBxW5lFa19JmBhMFzuYBUhCF95Sw0kXnHwVkuH7GyrPFp6RpW2OL+W4OAlXLLlfVpXj0XPvvpv7k1DXVdFVwgvbIv2clUd30Ji37GSIe9IKaAFQCY6SGBjQfafWe6v/KZx72bb7sF6/oWV4nv35tkkxYFUy6NklXMtQwB65sUoP9DOdxp4ZTOJiRmwezY30aL2jP8LtlqFnmcKQGTd1JRBlJGye7VXa8O+V8eTsbpBK/0lCZZMm0t+1PWREpieDUFVpKpbWxk98begDtjUcc9JtL4t4APFZRj4eq7gQvpghFihsgRwg0R1R+m++MElG/jOdZCS8lqMUKfikKBA4dDJPW8Ovq0gHpLV1hpq7WwfIkSUZAz7ZULenTjQy9RmasjNRKgxsPCrP48P1fVRrgzjSy4ZA43mci90sJTH8WdSYpEDw4pvGtH5M=
  - secure: U6FG4YOaktya4m88jhxPy+Nia6YN++QtFXCgR6TqD49NP0UuZ8JPIVMwdr/m1aS8HedotxPsZfLRU/50TcTJSGx5+wuZlLvMPqcSo2JHuTrH0BnLI3j5I8fJlzJqWCrtdJXc7BDR/cJS9wFdcq+fmFAEm2ZtSiYEo0slhHvMN1SQ6jUbtvpNmcEpQwrJeTmBnrD3IkHKcNTeTjzH/7yxD4Xna6AVVRladyv+xS8mozNZlIf2fCJY7QXLeP5rY8bxnoHGqVU2DX3u0YzL0mVMiaWs92//Xp4icbHvSlOsKhpKtuu7jhZGafoQICcPg1pzlmlqI9xPOfoxwOQ7SCzA7EGM7odPk5fWBUoz+wRUALzwTy+VX5oeVWy7UEwCydENw2lPKRJqjRpa9s2sAGHgoXkRKpXAYQKJWfsDUQvzhySnOKgvfjS/Oe+kk7osiXHHxwYL0jhAIC4Vn3VletxAZp01V6BHLE/uHjbNc8wealHppYTs8lZOwOAh98+5qwoBrTvp/H3utJIu1Ywf+v0Iww+PKgiyPwByHKVRpgdB4+rAaXvPMGeTERW37j9pHiEyr/qcwmPftBOBUpMfNjtmb2ROgpEzrwf+w43SeBHiTO3aeyw6WxH6nWKMcsy35OZnNbOJAur0aEd+AZkUtbzldm+7UOEoRr5N+6l+2h8hJWE=
  - secure: kQgRlcZ4F9V5wsu+i99dnSbDmsamTWlJWlsA1M/Pf+aL3icQ+YDjkAvvFKmY/HPG6WJfG6PLaUzSjZSHvL6GOqHxAx2V8NP8L3UKwtKMfkRgyFDlpeszwCMXb85xhq/DjTC8k+on/pZBPG5IvbS00VzhUsK+Q9HTbF/eO0n2bzcadklh5h4f0B1eGve0n/jOqc0Tv4QFNwPHZyx+kt8NpaSeuL1MQj5cXjkbBApECXg7FdyeYHkffTXfMGvKcRCYCWB2e/3KWTykuE+twfq8tEboHwXWETokd7pxoRymFDTQKoCHLNDoEvGOIM6EQxbp5SxN3SXweXYzG0pmA9TZZODtO6HQZmABgmd7+ljplQt3OdmX6/krWuFM+lLke/4RN9Ahq9uJKQ2ti+JhXZrwcPmDZzWX6e53NYv7YFCD1mFw6y8bgDgzUAnaq64/K8gSjdnA6I3tJ8UXEbrjcrKPIjtzzwBHUAWADFfIPBYqav+/XFm/l6s/2Qy838HCzq/vAcq707ZYECG4f4DtQV4LdkiNIXBuYmNhonQPrqiD+/MqgP+rvbup/tmKzG8RxE1lSXjzX4pNClJl6XRexpAsEAaAfqA0ZZcD6d7yjipGVb0m1Q5jCQT/xzcsU/gEWKt8D3L8lF/MO0jBkCxSIzMiSlI63yhJSRwKgF5DjPZpcHE=
  - secure: N9oVpzIU8cXZeB9X18+uXfouoVUP2z+x7x/9BCqRAq4wv3OjZwNZEw9pPVXTjtADUfWiEaBu1YLAWHkdQK4W1cGr/BWDpfVj2K4DsB8R/5vaBAnFJ8lWGLESP+IqIaGO19te2sRXFzg8XQeo8X+TSW9axZ1C10MAUiAqZ/qF5M17UtEq+39DQBmGC2c4g0HnG91Lbxbo6XWPFIXfemi+gFnEhNVzWspM/02zMHGDYas/aVNs5Bdt7Sco6eGqestV+EzbDYui+Sg78JG+I9x0qky8F7ssKNGh0sC14JdLsr9Ztj4gXAIvKVkTMQDhiNBgJAFFcQ9RKIVa4qfge1az7oXSIDN6mRn8owH2Dgi8iwqJLwmrtHR13OEIoLG292DK+LrSXzoExD3ektgbLTWV8klRq5eFdFPeXmYi9Edh2/9sPHnpRofHTsstgk24WF957X/gc7Nc8zLR6fAHvtyz3BeOuJvNCtwbbRJJU8np5St5kqGmQHA2vlK79DjHeb/aa1TruGYSocXIWD6VdN3MPFm2SjaMdcQXZaY+nULRFuhpYN3oBJUlxg9XxngqvQviGpU402RuIkDRsOgQn7Hc67xAnE6PjftdY+9tqsjYL6hjb/CJnW7zGLNlGdFnRFfqGChsmwQWlf9bohNlKujZ547ywcwyxEyMiISWOYo3sJU=
